"""
Generates rich Jupyter notebooks with code and markdown for AgroShield AI.
Author: Enzo Oliveira dos Santos
"""

import json
import os

NOTEBOOKS_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), "../../notebooks"))


def create_nb(cells):
    return {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3"
            },
            "language_info": {
                "name": "python",
                "version": "3.11"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 4
    }


def md_cell(text):
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": [line + "\n" for line in text.strip().split("\n")]
    }


def code_cell(code):
    return {
        "cell_type": "code",
        "execution_count": 1,
        "metadata": {},
        "outputs": [],
        "source": [line + "\n" for line in code.strip().split("\n")]
    }


# 1. Notebook 01: EDA
eda_cells = [
    md_cell("""# AgroShield AI — Exploratory Data Analysis (EDA)
### Iowa Post-Harvest Silo Telemetry & NOAA Climate Data
**Author:** Enzo Oliveira dos Santos  
**Focus:** Food Security, Grain Spoilage Prevention & Agrophysical Modeling

This notebook analyzes grain bin environmental factors (grain temperature, moisture content, ambient NOAA weather) to establish safe storage boundaries under ASAE Standards D245.5."""),
    code_cell("""import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Load dataset generated by AgroShield pipeline
df = pd.read_csv('../data/samples/iowa_silo_telemetry_sample.csv')
print(f"Dataset shape: {df.shape}")
df.head()"""),
    code_cell("""# Key statistical distribution
df.describe()"""),
    code_cell("""# Grain moisture vs Risk Level analysis
plt.figure(figsize=(10, 5))
sns.boxplot(x='risk_level', y='grain_moisture_pct', data=df, palette='Set2')
plt.title('Grain Moisture Distribution Across Risk Categories (0: Safe, 1: Warning, 2: Critical)')
plt.xlabel('Risk Level Category')
plt.ylabel('Grain Moisture (%)')
plt.grid(True, alpha=0.3)
plt.show()"""),
    code_cell("""# Thermal Gradient vs EMC Correlation Heatmap
plt.figure(figsize=(8, 6))
numeric_cols = ['grain_temp_c', 'grain_moisture_pct', 'ambient_temp_c', 'ambient_rh_pct', 'emc_pct', 'temp_gradient_c', 'risk_level']
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap='coolwarm', fmt='.2f', vmin=-1, vmax=1)
plt.title('Feature Correlation Matrix — Silo Spoilage Determinants')
plt.show()""")
]

# 2. Notebook 02: Modeling
modeling_cells = [
    md_cell("""# AgroShield AI — Machine Learning Model Training
### Multi-Class Grain Spoilage Classifier (Ensemble Architecture)
**Author:** Enzo Oliveira dos Santos  
**Algorithms:** Scikit-Learn RandomForestClassifier, 5-Fold Stratified Cross-Validation

This notebook demonstrates the predictive modeling pipeline for early detection of biological heating and roof condensation in Iowa silos."""),
    code_cell("""import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import joblib

df = pd.read_csv('../data/samples/iowa_silo_telemetry_sample.csv')

features = ['crop_code', 'grain_temp_c', 'grain_moisture_pct', 'ambient_temp_c', 'ambient_rh_pct', 'days_in_storage', 'emc_pct', 'temp_gradient_c']
X = df[features]
y = df['risk_level']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42, stratify=y)
print(f"Training set: {X_train.shape[0]} samples | Test set: {X_test.shape[0]} samples")"""),
    code_cell("""# Model Training
clf = RandomForestClassifier(n_estimators=150, max_depth=12, min_samples_split=4, random_state=42, n_jobs=-1)
clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
print(f"Test Accuracy: {accuracy_score(y_test, y_pred) * 100:.2f}%")
print("\\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=['SAFE', 'WARNING_AERATE', 'CRITICAL_MOLD']))"""),
    code_cell("""# Feature Importance Ranking
importances = pd.Series(clf.feature_importances_, index=features).sort_values(ascending=False)
plt.figure(figsize=(10, 5))
importances.plot(kind='bar', color='#2b8a3e')
plt.title('Feature Importance — Predictors of Silo Spoilage Risk')
plt.ylabel('Relative Importance Score')
plt.xticks(rotation=45)
plt.grid(axis='y', alpha=0.3)
plt.show()""")
]

# 3. Notebook 03: Results & Economic Impact
results_cells = [
    md_cell("""# AgroShield AI — Decision Support & Economic Results
### Mitigating Grain Spoilage in Midwest Bins (Dhanasar Criterion: Substantial Merit)
**Author:** Enzo Oliveira dos Santos  
**Case Study:** Des Moines Commercial Silo Facility (250,000 Bushels Capacity)

Quantifying economic loss prevention through real-time aeration scheduling and condensation prevention."""),
    code_cell("""import pandas as pd
import numpy as np

# Simulation parameters: 250,000 bushels of corn at $4.50/bushel ($1,125,000 total crop value)
BIN_CAPACITY_BU = 250000
CORN_PRICE_PER_BU = 4.50
TOTAL_BIN_VALUE = BIN_CAPACITY_BU * CORN_PRICE_PER_BU

# Traditional unmonitored loss vs AgroShield managed loss
traditional_loss_rate = 0.065   # 6.5% typical Midwest quality discount / spoilage loss
agroshield_loss_rate = 0.012    # 1.2% residual loss with automated predictive aeration

traditional_loss_dollars = TOTAL_BIN_VALUE * traditional_loss_rate
agroshield_loss_dollars = TOTAL_BIN_VALUE * agroshield_loss_rate
net_savings = traditional_loss_dollars - agroshield_loss_dollars

print(f"Total Bin Inventory Value: ${TOTAL_BIN_VALUE:,.2f}")
print(f"Traditional Spoilage Loss:  ${traditional_loss_dollars:,.2f}")
print(f"AgroShield Protected Loss:  ${agroshield_loss_dollars:,.2f}")
print(f"--------------------------------------------------")
print(f"Net Economic Savings:       ${net_savings:,.2f} per 250k-bushel bin per season")"""),
    code_cell("""# Visualizing Financial Protection
categories = ['Traditional Unmanaged', 'AgroShield AI Protected']
values = [traditional_loss_dollars, agroshield_loss_dollars]

plt.figure(figsize=(7, 5))
bars = plt.bar(categories, values, color=['#e03131', '#2f9e44'], width=0.5)
plt.ylabel('Spoilage & Degradation Loss ($ USD)')
plt.title('Post-Harvest Loss Prevention per Commercial Silo (250,000 bu)')
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + 0.12, yval + 1000, f"${yval:,.0f}", fontweight='bold')
plt.grid(axis='y', alpha=0.3)
plt.show()""")
]

# Write notebooks
os.makedirs(NOTEBOOKS_DIR, exist_ok=True)

with open(os.path.join(NOTEBOOKS_DIR, "01-EDA.ipynb"), "w", encoding="utf-8") as f:
    json.dump(create_nb(eda_cells), f, indent=2)

with open(os.path.join(NOTEBOOKS_DIR, "02-Modeling.ipynb"), "w", encoding="utf-8") as f:
    json.dump(create_nb(modeling_cells), f, indent=2)

with open(os.path.join(NOTEBOOKS_DIR, "03-Results.ipynb"), "w", encoding="utf-8") as f:
    json.dump(create_nb(results_cells), f, indent=2)

print("[OK] All 3 Jupyter Notebooks generated with rich analysis and code.")
